name: Save Absen Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'JSON data for the absen entry'
        required: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create or update JSON file
        run: |
          # Buat file JSON jika belum ada dengan array kosong
          if [ ! -f absen_log.json ]; then
            echo "[]" > absen_log.json
          fi

          # Baca data JSON yang sudah ada
          CURRENT_DATA=$(cat absen_log.json)
          
          # Dapatkan data baru dari input workflow
          NEW_DATA='${{ github.event.inputs.data }}'

          # Gabungkan data baru ke dalam array yang sudah ada
          # Ini adalah langkah yang rumit karena Bash tidak menangani JSON dengan baik
          # Lebih baik menggunakan jq, tapi kita pakai metode manual yang sederhana
          
          # Hapus tanda ']' terakhir dari string JSON
          CURRENT_DATA_TRIMMED=${CURRENT_DATA%?}

          # Gabungkan data baru (dengan tanda koma jika tidak kosong)
          if [ "${CURRENT_DATA_TRIMMED}" == "[" ]; then
            COMBINED_DATA="${CURRENT_DATA_TRIMMED}${NEW_DATA}]"
          else
            COMBINED_DATA="${CURRENT_DATA_TRIMMED},${NEW_DATA}]"
          fi
          
          # Tulis kembali data gabungan ke file
          echo "${COMBINED_DATA}" > absen_log.json

      - name: Commit and Push changes
        uses: actions-js/push@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: 'Update absen log from web app'
          force: false
          
