name: Save Absen Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'JSON data for the absen entry'
        required: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create or update JSON file
        run: |
          if [ ! -f absen_log.json ]; then
            echo "[]" > absen_log.json
          fi

          CURRENT_DATA=$(cat absen_log.json)
          NEW_DATA='${{ github.event.inputs.data }}'
          
          CURRENT_DATA_TRIMMED=${CURRENT_DATA%?}

          if [ "${CURRENT_DATA_TRIMMED}" == "[" ]; then
            COMBINED_DATA="${CURRENT_DATA_TRIMMED}${NEW_DATA}]"
          else
            COMBINED_DATA="${CURRENT_DATA_TRIMMED},${NEW_DATA}]"
          fi
          
          echo "${COMBINED_DATA}" > absen_log.json

      - name: Commit and Push changes
        uses: actions-js/push@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          commit_message: 'Update absen log from web app' # Ganti 'message' menjadi 'commit_message'
          force: false
