name: Update Absen Data

on:
  repository_dispatch:
    types: [absen_request]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create or update JSON file
        run: |
          # Ambil data yang dikirim dari payload
          echo 'Data Absen yang diterima:'
          echo "${{ github.event.client_payload.data }}" | jq '.'

          # Baca file JSON yang sudah ada
          CURRENT_DATA=$(cat absensi.json)
          
          # Tambahkan data baru ke file JSON
          UPDATED_DATA=$(echo "${CURRENT_DATA}" | jq --argjson new_entry "${{ github.event.client_payload.data }}" '. + [$new_entry]')
          
          # Tulis data yang diperbarui kembali ke file
          echo "${UPDATED_DATA}" > absensi.json
          
          echo "File absensi.json berhasil diperbarui."

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Absen baru: ${{ github.event.client_payload.name }}"
